// CC(크리에이티브 커먼즈) 사진 매핑의 단일 출처. ②에서 점진적으로 채운다.
// 이미지 바이너리는 공개 데이터 repo(ordinary-garden-data/codex/)에 두고 CC_BASE로 참조한다.

export interface CcPhoto {
  file: string // 데이터 repo 내 파일명 (예: "hydrangea-macrophylla.jpg")
  author: string // 저작자 표시
  license: string // 예: "CC BY 4.0" | "CC BY-SA 4.0" | "CC0" | "Public Domain"
  licenseUrl: string // 라이선스 전문 링크
  sourceUrl: string // 원본 출처(예: 위키미디어 파일 페이지)
  title?: string
}

export const CC_BASE = 'https://rakonteto.github.io/ordinary-garden-data/codex/'

/** 종 id → CC 사진. ②에서 점진 누적(현재: 수국 5종·작약 5종). 출처=위키미디어 공용, 자유 라이선스만(CC0·PD·BY·BY-SA). */
export const ccPhotos: Record<string, CcPhoto> = {
  'hydrangea-macrophylla': {
    file: 'hydrangea-macrophylla.jpg',
    author: 'Michele Dorsey Walfred',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Blue_Hydrangea_Mathilda_Gutges_-blueflower.jpg',
    title: 'Blue Hydrangea (Mathilda Gutges)',
  },
  'hydrangea-serrata': {
    file: 'hydrangea-serrata.jpg',
    author: 'Motohiro Sunouchi',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Hydrangea_serrata_var._serrata_%27%E4%BB%81%E6%B7%80%E5%85%AB%E9%87%8D_-_Niyodo_Yae%27_20260606_193423.jpg',
    title: 'Hydrangea serrata (Niyodo Yae)',
  },
  'hydrangea-paniculata': {
    file: 'hydrangea-paniculata.jpg',
    author: 'Strubbl',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Bl%C3%BCte_der_Rispen-Hortensie_2024-08-22.jpg',
    title: 'Blüte der Rispen-Hortensie',
  },
  'hydrangea-arborescens': {
    file: 'hydrangea-arborescens.jpg',
    author: 'Mike Peel (www.mikepeel.net)',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:At_Dunham_Massey_2023_61.jpg',
    title: 'At Dunham Massey (Annabelle-type)',
  },
  'hydrangea-quercifolia': {
    file: 'hydrangea-quercifolia.jpg',
    author: 'Denis.prévôt',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hydrangea_quercifolia_-_Fleurs-2.jpg',
    title: 'Hydrangea quercifolia (Fleurs)',
  },
  // ── 작약·모란 5종 (② 둘째 배치) ─────────────────────────────
  'paeonia-lactiflora': {
    file: 'paeonia-lactiflora.jpg',
    author: 'Joanna Boisse',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Atlas_roslin_pl_Piwonia_chi%C5%84ska_10035_7511.jpg',
    title: 'Paeonia lactiflora (작약)',
  },
  'paeonia-suffruticosa': {
    file: 'paeonia-suffruticosa.jpg',
    author: 'Andrey Butko',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ab_plant_483.jpg',
    title: 'Paeonia suffruticosa (모란)',
  },
  'paeonia-itoh': {
    file: 'paeonia-itoh.jpg',
    author: 'F. D. Richards',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Paeonia_%27Bartzella%27_6_2021_Itoh-_(51218937473).jpg",
    title: "Paeonia Itoh 'Bartzella' (이토 작약)",
  },
  'paeonia-japonica': {
    file: 'paeonia-japonica.jpg',
    author: 'Alpsdake',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Paeonia_japonica_flower.JPG',
    title: 'Paeonia japonica (백작약)',
  },
  'paeonia-obovata': {
    file: 'paeonia-obovata.jpg',
    author: 'Motohiro Sunouchi',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Paeonia_obovata_%27Honoh_-_%E7%82%8E%27_Maxim.,_M%C3%A9m._Acad._Imp._Sci._St.-P%C3%A9tersbourg_Divers_Savans_9_39_(1859)_(40905468113).jpg",
    title: "Paeonia obovata 'Honoh' (산작약)",
  },
  // ── 구근 10종 (② 셋째 배치) ─────────────────────────────
  'tulip-main': {
    file: 'tulip-main.jpg',
    author: 'Dietmar Rabich',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:M%C3%BCnster,_Wolbeck,_Johannes_Blumenfelder,_Tulpen_--_2021_--_7833.jpg',
    title: 'Tulipa (튤립)',
  },
  'daffodil-main': {
    file: 'daffodil-main.jpg',
    author: 'JackyM59',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Fleur_de_narcisse_jaune_-_(Narcissus_pseudonarcissus).jpg',
    title: 'Narcissus (수선화)',
  },
  'hyacinth-main': {
    file: 'hyacinth-main.jpg',
    author: 'Sakartvelo',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Blue_flowers_Hyacinthus_orientalis.JPG',
    title: 'Hyacinthus orientalis (히아신스)',
  },
  'crocus-main': {
    file: 'crocus-main.jpg',
    author: 'Dirk Liesch',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Biene_im_Flug_an_Wildkrokus.jpg',
    title: 'Crocus (크로커스)',
  },
  'muscari-main': {
    file: 'muscari-main.jpg',
    author: 'OndraCalta trees',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mod%C5%99enec_(arm%C3%A9nsk%C3%BD%3F).jpg',
    title: 'Muscari (무스카리)',
  },
  'lily-main': {
    file: 'lily-main.jpg',
    author: 'Mike Peel (www.mikepeel.net)',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:At_Shugborough_2024_026.jpg',
    title: 'Lilium (백합·나리)',
  },
  'red-spider-lily-main': {
    file: 'red-spider-lily-main.jpg',
    author: 't.kunikuni',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cluster_amaryllis3.jpg',
    title: 'Lycoris radiata (꽃무릇·석산)',
  },
  'gladiolus-main': {
    file: 'gladiolus-main.jpg',
    author: 'Aw58',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mieczyki_w_wazonie_-_16.08.2024.jpg',
    title: 'Gladiolus (글라디올러스)',
  },
  'dahlia-main': {
    file: 'dahlia-main.jpg',
    author: 'Bengt Nyman from Vaxholm, Sweden',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dahlia_(52143078092).jpg',
    title: 'Dahlia (다알리아)',
  },
  'canna-main': {
    file: 'canna-main.jpg',
    author: 'PapiPijuan',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Canna_Indica_Flower.jpg',
    title: 'Canna (칸나)',
  },
  // ── 한해살이 10종 (② 넷째 배치) ─────────────────────────────
  'petunia-main': {
    file: 'petunia-main.jpg',
    author: 'Anik Sarker',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Surfinia_Purple_Flower.jpg',
    title: 'Petunia (페튜니아)',
  },
  'marigold-main': {
    file: 'marigold-main.jpg',
    author: 'Sixflashphoto',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Inniswood_-_Tagetes_erecta_1.jpg',
    title: 'Tagetes (메리골드)',
  },
  'pansy-main': {
    file: 'pansy-main.jpg',
    author: 'Agnieszka Kwiecień, Nova',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Viola_x_wittrockiana_%27Carneval_Cherry%27_Bratek_ogrodowy_2018-04-15_01_(2).jpg",
    title: 'Viola × wittrockiana (팬지·비올라)',
  },
  'balsam-main': {
    file: 'balsam-main.jpg',
    author: 'Astari28',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bunga_Pacar_Air.png',
    title: 'Impatiens balsamina (봉선화·봉숭아)',
  },
  'cosmos-main': {
    file: 'cosmos-main.jpg',
    author: 'Juan Carlos Fonseca Mata',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mirasol_(Cosmos_bipinnatus).jpg',
    title: 'Cosmos bipinnatus (코스모스)',
  },
  'portulaca-main': {
    file: 'portulaca-main.jpg',
    author: 'Darkpeanut',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fleur_Portulaca_grandiflora.jpg',
    title: 'Portulaca grandiflora (채송화)',
  },
  'zinnia-main': {
    file: 'zinnia-main.jpg',
    author: 'Ermell',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Zinnienbl%C3%BCte_Zinnia_elegans_stack15_20190722-RM-7222254.jpg',
    title: 'Zinnia elegans (백일홍·백일초)',
  },
  'sunflower-main': {
    file: 'sunflower-main.jpg',
    author: 'Andreas Eichler',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:2017.07.18.-01-Ahrensdorf_Rietz-Neuendorf--Sonnenblumenfeld.jpg',
    title: 'Helianthus annuus (해바라기)',
  },
  'celosia-main': {
    file: 'celosia-main.jpg',
    author: 'ProtoplasmaKid',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Celosia_cristata_(terciopelo)_-_flor_de_D%C3%ADa_de_Muertos_-_Closeup_-_2.jpg',
    title: 'Celosia (맨드라미)',
  },
  'scarlet-sage-main': {
    file: 'scarlet-sage-main.jpg',
    author: 'Maurice07',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Flower_-_Istanbul.jpg',
    title: 'Salvia splendens (샐비어·사루비아)',
  },
  // ── 숙근 11종 (② 다섯째 배치) ─────────────────────────────
  'chrysanthemum-main': {
    file: 'chrysanthemum-main.jpg',
    author: 'Ermell',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Chrysantheme_rot_tautropfen_-20191024-RM-102058.jpg',
    title: 'Chrysanthemum × morifolium (국화)',
  },
  'hosta-main': {
    file: 'hosta-main.jpg',
    author: 'Mike Peel (www.mikepeel.net)',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:At_Berrington_Hall_2022_116.jpg',
    title: 'Hosta (옥잠화·호스타)',
  },
  'iris-main': {
    file: 'iris-main.jpg',
    author: 'Ermell',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Iris_versicolor_-20200620-RM-100933.jpg',
    title: 'Iris (붓꽃·아이리스)',
  },
  'gujeolcho-main': {
    file: 'gujeolcho-main.jpg',
    author: 'Averater',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Chrysanthemum_zawadskii_ssp._acutilobum_var._alpinum_GotBot_2015_001.jpg',
    title: 'Dendranthema zawadskii (구절초)',
  },
  'korean-aster-main': {
    file: 'korean-aster-main.jpg',
    author: 'Dalgial (파생: Sang Seo)',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:%EB%B2%8C%EA%B0%9C%EB%AF%B8%EC%B7%A8_%EA%B0%80%EA%B9%8C%EC%9D%B4-2.JPG',
    title: 'Aster koraiensis (벌개미취)',
  },
  'coreopsis-main': {
    file: 'coreopsis-main.jpg',
    author: 'houroumono',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Coreopsis_lanceolata_(14254188771).jpg',
    title: 'Coreopsis (금계국·큰금계국)',
  },
  'rudbeckia-main': {
    file: 'rudbeckia-main.jpg',
    author: 'Sander van der Wel from Netherlands',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Autumn_flowers_(10376232316).jpg',
    title: 'Rudbeckia (루드베키아)',
  },
  'echinacea-main': {
    file: 'echinacea-main.jpg',
    author: 'Krzysztof Golik',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Echinacea_purpurea_in_Jardin_botanique_de_la_Charme_01.jpg',
    title: 'Echinacea purpurea (에키네시아)',
  },
  'shasta-daisy-main': {
    file: 'shasta-daisy-main.jpg',
    author: 'Sankar 1995',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:White_Shasta_Daisies-_Shola_Gardens_-_Kotagiri.jpg',
    title: 'Leucanthemum × superbum (샤스타데이지)',
  },
  'hollyhock-main': {
    file: 'hollyhock-main.jpg',
    author: 'S.G.S.',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Alcea_ficifolia_IMG_1983.jpg',
    title: 'Alcea (접시꽃)',
  },
  'balloon-flower-main': {
    file: 'balloon-flower-main.jpg',
    author: 'Krzysztof Golik',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Platycodon_grandiflorus_in_Jardin_botanique_de_la_Charme.jpg',
    title: 'Platycodon grandiflorus (도라지)',
  },
  // ── 덩굴·화목 11종 (② 여섯째 배치) ─────────────────────────────
  'clematis-main': {
    file: 'clematis-main.jpg',
    author: 'Bengt Nyman from Vaxholm, Sweden',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:A7R09085_(52138013652).jpg',
    title: 'Clematis (클레마티스)',
  },
  'trumpet-vine-main': {
    file: 'trumpet-vine-main.jpg',
    author: 'Zythème',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Campsis_grandiflora,_2.jpg',
    title: 'Campsis grandiflora (능소화)',
  },
  'wisteria-main': {
    file: 'wisteria-main.jpg',
    author: 'Tangopaso',
    license: 'Public Domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Abbaye_de_L%C3%A9rins,_wisteria_in_the_yard_of_the_church.jpg',
    title: 'Wisteria floribunda (등나무)',
  },
  'morning-glory-main': {
    file: 'morning-glory-main.jpg',
    author: 'Melgisan',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ipomoea_Nil_Flower.jpg',
    title: 'Ipomoea nil (나팔꽃)',
  },
  'azalea-jindalrae-main': {
    file: 'azalea-jindalrae-main.jpg',
    author: '최광모',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:20150331%EC%B5%9C%EA%B4%91%EB%AA%A8123.jpg',
    title: 'Rhododendron mucronulatum (진달래)',
  },
  'azalea-cheoljjuk-main': {
    file: 'azalea-cheoljjuk-main.jpg',
    author: 'Cephas',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rhododendron_schlippenbachii_JRVdH_07.jpg',
    title: 'Rhododendron schlippenbachii (철쭉)',
  },
  'camellia-main': {
    file: 'camellia-main.jpg',
    author: 'Motohiro Sunouchi',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Camellia_japonica_%27Izumo-no-okuni_%E5%87%BA%E9%9B%B2%E9%98%BF%E5%9B%BD%27_L.-_Sp._Pl._2-_698_(1753)_20240216_174759.jpg",
    title: 'Camellia japonica (동백)',
  },
  'rose-of-sharon-main': {
    file: 'rose-of-sharon-main.jpg',
    author: 'Sevayuu',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Hibiscus_syriacus_purple_flower_in_Tashkent_Region.jpg',
    title: 'Hibiscus syriacus (무궁화)',
  },
  'lilac-main': {
    file: 'lilac-main.jpg',
    author: 'Joselodos',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Syringa_vulgaris_in_bloom.jpg',
    title: 'Syringa (라일락·수수꽃다리)',
  },
  'magnolia-main': {
    file: 'magnolia-main.jpg',
    author: 'Susanne Nilsson',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Magnolia_(34982957795).jpg',
    title: 'Magnolia (목련)',
  },
  'forsythia-main': {
    file: 'forsythia-main.jpg',
    author: 'Palberts9956',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Yellow_Flowers_2020.jpg',
    title: 'Forsythia koreana (개나리)',
  },
  // ── 장미 11계통 (② 일곱째 배치). 한국 육성종은 위키미디어에 확증 가능한
  //    품종 사진이 없어 매핑하지 않고 이모지 폴백으로 둔다. ───────────────
  'rosa-hybrid-tea': {
    file: 'rosa-hybrid-tea.jpg',
    author: 'T.Kiya',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Rose,_Hommsrge_a_Barbara,_%E3%83%90%E3%83%A9,_%E3%82%AA%E3%83%9E%E3%83%BC%E3%82%B8%E3%83%A5_%E3%82%A2_%E3%83%90%E3%83%AB%E3%83%90%E3%83%A9_-_Flickr_-_T.Kiya.jpg',
    title: "Rosa 'Hommage à Barbara' (하이브리드 티)",
  },
  'rosa-floribunda': {
    file: 'rosa-floribunda.jpg',
    author: 'Krishna k. sahh',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:White_and_pink_shrub_roses.jpg',
    title: 'Rosa Floribunda (플로리분다)',
  },
  'rosa-grandiflora': {
    file: 'rosa-grandiflora.jpg',
    author: 'T.Kiya from Japan',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Rose,_Queen_Elizabeth,_%E3%83%90%E3%83%A9,_%E3%82%AF%E3%82%A4%E3%83%BC%E3%83%B3_%E3%82%A8%E3%83%AA%E3%82%B6%E3%83%99%E3%82%B9,_(13183072693).jpg',
    title: "Rosa 'Queen Elizabeth' (그란디플로라)",
  },
  'rosa-polyantha': {
    file: 'rosa-polyantha.jpg',
    author: 'T.Kiya from Japan',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Rose,The_Fairy,%E3%83%90%E3%83%A9,%E3%82%B6%E3%83%BB%E3%83%95%E3%82%A7%E3%82%A2%E3%83%AA%E3%83%BC,_(8188560254).jpg',
    title: "Rosa 'The Fairy' (폴리안타)",
  },
  'rosa-shrub': {
    file: 'rosa-shrub.jpg',
    author: 'Acabashi',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:%27Rosa_Sadlers_Wells%27_modern_shrub_rose_Capel_Manor_College_Gardens_Enfield_London_England.jpg',
    title: 'Rosa Modern Shrub (모던 슈러브)',
  },
  'rosa-miniature': {
    file: 'rosa-miniature.jpg',
    author: 'Aniol',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mini_roser_florit.JPG',
    title: 'Rosa Miniature (미니어처)',
  },
  'rosa-climbing': {
    file: 'rosa-climbing.jpg',
    author: 'Acabashi',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Pale_pink_climbing_rose_at_Harlow_Museum_%26_Walled_Gardens,_Essex_02.jpg',
    title: 'Rosa Climbing (클라이밍)',
  },
  'rosa-rambler': {
    file: 'rosa-rambler.jpg',
    author: 'Geolina163',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rosa_Kiftsgate_Rosarium_Baden_01.jpg',
    title: "Rosa 'Kiftsgate' (램블러)",
  },
  'rosa-english': {
    file: 'rosa-english.jpg',
    author: 'F. D. Richards from Clinton, MI',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Rosa_%27Ausgrab%27_-THE_ALNWICK_ROSE-_6_2021_DAR-_(51260869904).jpg',
    title: "Rosa 'The Alnwick Rose' (잉글리시·데이비드 오스틴)",
  },
  'rosa-old-garden': {
    file: 'rosa-old-garden.jpg',
    author: 'Alexander Rahm',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Essig-Rose_(Haager_Stra%C3%9Fe,_Neuendettelsau)_20250617_072357.jpg',
    title: 'Rosa gallica (올드 가든 로즈)',
  },
  'rosa-species': {
    file: 'rosa-species.jpg',
    author: 'Юрий Д.К.',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Rosa_rugosa_in_Repinsky_Square,_Moscow,_May_2026_6.jpg',
    title: 'Rosa rugosa (원종·해당화)',
  },
  // ── 과수·교목 14종 (② 여덟째 배치). 비화훼 첫 그룹.
  //    대추·매실·모과·석류는 자유 라이선스 익은 사진이 없어 종이 확증된
  //    풋과실(가지에 달린)로 정직하게 매핑한다. ───────────────────────
  'apple-main': {
    file: 'apple-main.jpg',
    author: 'Vici',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:%22Konsta%22_apples_grown_in_Finland_(K01561).jpg',
    title: 'Malus domestica (사과)',
  },
  'pear-main': {
    file: 'pear-main.jpg',
    author: 'harum.koh from Kobe city, Japan',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Asian_Pear_(Pyrus_pyrifolia)_(21650080978).jpg',
    title: 'Pyrus pyrifolia (배)',
  },
  'persimmon-sweet': {
    file: 'persimmon-sweet.jpg',
    author: 'Frank Schulenburg',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fuyu_persimmon_fruits,_one_cut_open.jpg',
    title: 'Diospyros kaki (단감)',
  },
  'persimmon-astringent': {
    file: 'persimmon-astringent.jpg',
    author: 'Tduk Alex Lozupone',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hachiya1.jpg',
    title: 'Diospyros kaki (떫은감)',
  },
  'jujube-main': {
    file: 'jujube-main.jpg',
    author: 'Yercaud-elango',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ziziphus_jujuba-1-rasipuram-namakkal-India.jpg',
    title: 'Ziziphus jujuba (대추)',
  },
  'fig-main': {
    file: 'fig-main.jpg',
    author: 'Ivar Leidus',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fig_(Ficus_carica)_fruit_halved.jpg',
    title: 'Ficus carica (무화과)',
  },
  'peach-main': {
    file: 'peach-main.jpg',
    author: 'Harry Van den Bulck',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Peach_tree_branch_with_fruits.jpg',
    title: 'Prunus persica (복숭아)',
  },
  'plum-main': {
    file: 'plum-main.jpg',
    author: 'Ivar Leidus',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Plums_African_Rose_-_whole,_halved_and_slice.jpg',
    title: 'Prunus salicina (자두)',
  },
  'maesil-main': {
    file: 'maesil-main.jpg',
    author: 'Neux-Neux',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Prunus_mume_f._pleiocarpa_(fruit).jpg',
    title: 'Prunus mume (매실)',
  },
  'apricot-main': {
    file: 'apricot-main.jpg',
    author: 'Juan Emilio Prades Bel',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Albaricoques_(Prunus_armeniaca).jpg',
    title: 'Prunus armeniaca (살구)',
  },
  'korean-cherry-main': {
    file: 'korean-cherry-main.jpg',
    author: 'Sadopaul',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Changdeokgung_Manchu_cherry_in_2026.jpg',
    title: 'Prunus tomentosa (앵두)',
  },
  'cherry-main': {
    file: 'cherry-main.jpg',
    author: 'DidierFy',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Prunus_avium_06.2025_(1).jpg',
    title: 'Prunus avium (체리·양앵두)',
  },
  'quince-main': {
    file: 'quince-main.jpg',
    author: 'Nesnad',
    license: 'CC BY 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Pseudocydonia_sinensis_July_02_2021_09-23AM.jpeg',
    title: 'Pseudocydonia sinensis (모과)',
  },
  'pomegranate-main': {
    file: 'pomegranate-main.jpg',
    author: 'Erol Zafer Ahmed',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pomegranate_on_the_Branch.jpg',
    title: 'Punica granatum (석류)',
  },
  // ── 베리·덩굴 과수 12종 (② 아홉째 배치). 비화훼 둘째 그룹. 열매가 대표라
  //    열매 편향으로 골랐다. 복분자(Rubus coreanus)는 위키미디어에 종 라벨
  //    열매 사진이 한 장뿐이라 그것(붉은·검은 열매 가지)으로, 구기자는 종
  //    확증 사진이 꽃뿐이라 선명한 구기자(고지) 열매로 정직하게 매핑한다. ──
  'blueberry-highbush': {
    file: 'blueberry-highbush.jpg',
    author: 'Aw58',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Bor%C3%B3wka_ameryka%C5%84ska_-_2023.08.12.jpg',
    title: 'Vaccinium corymbosum (블루베리)',
  },
  'grape-main': {
    file: 'grape-main.jpg',
    author: 'Jules Verne Times Two',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Bunch_of_grapes_amidst_vine_leaves,_Ponte_de_Sor_(approx._GPS_location)_julesvernex2.jpg',
    title: 'Vitis (포도)',
  },
  'kiwi-deliciosa': {
    file: 'kiwi-deliciosa.jpg',
    author: 'Ivar Leidus',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kiwifruit_cross_section.jpg',
    title: 'Actinidia deliciosa (참다래·그린키위)',
  },
  'kiwi-chinensis': {
    file: 'kiwi-chinensis.jpg',
    author: 'Ivar Leidus',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kiwifruit_%27Gold%27_cross_section.jpg",
    title: 'Actinidia chinensis (골드키위)',
  },
  'kiwi-arguta': {
    file: 'kiwi-arguta.jpg',
    author: 'anagoria',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:20240928_Kiwibeeren_-_actinidia_arguta_anagoria.jpg',
    title: 'Actinidia arguta (토종다래·하디키위)',
  },
  'raspberry-main': {
    file: 'raspberry-main.jpg',
    author: 'Ivar Leidus',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Raspberries_(Rubus_idaeus).jpg',
    title: 'Rubus idaeus (라즈베리)',
  },
  'blackberry-main': {
    file: 'blackberry-main.jpg',
    author: 'Ivar Leidus',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Blackberry_(Rubus_fruticosus).jpg',
    title: 'Rubus fruticosus (블랙베리)',
  },
  'bokbunja-main': {
    file: 'bokbunja-main.jpg',
    author: '성락 + 연주',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Korean_raspberry_2008.jpg',
    title: 'Rubus coreanus (복분자)',
  },
  'aronia-main': {
    file: 'aronia-main.jpg',
    author: 'MiraculixHB',
    license: 'Public Domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Aronia_berries.JPG',
    title: 'Aronia melanocarpa (아로니아)',
  },
  'goumi-main': {
    file: 'goumi-main.jpg',
    author: 'VoDeTan2 Dericks-Tan',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Elaeagnus_multiflora_Frucht.jpg',
    title: 'Elaeagnus multiflora (뜰보리수)',
  },
  'mulberry-main': {
    file: 'mulberry-main.jpg',
    author: 'Chiring chandan',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Morus_alba_(White_mulberry).jpg',
    title: 'Morus alba (오디·뽕나무)',
  },
  'goji-main': {
    file: 'goji-main.jpg',
    author: 'Jeon Sang O',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Goji_berries.jpg',
    title: 'Lycium chinense (구기자)',
  },
  // ② 열째 배치 = 채소(잎·양념) 15종(비화훼 셋째 그룹).
  'lettuce-main': {
    file: 'lettuce-main.jpg',
    author: 'Alpha0111',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:La_laitue_03.jpg',
    title: 'Lactuca sativa (상추)',
  },
  'spinach-main': {
    file: 'spinach-main.jpg',
    author: 'Cut angles',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Spinach_in_multiples.jpg',
    title: 'Spinacia oleracea (시금치)',
  },
  'crown-daisy-main': {
    file: 'crown-daisy-main.jpg',
    author: 'Krzysztof Ziarnek, Kenraiz',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Glebionis_coronaria_kz13.jpg',
    title: 'Glebionis coronaria (쑥갓)',
  },
  'chard-main': {
    file: 'chard-main.jpg',
    author: 'Dietmar Rabich',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:M%C3%BCnster,_Botanischer_Garten,_Mangold_--_2019_--_7369.jpg',
    title: 'Beta vulgaris var. cicla (근대)',
  },
  'perilla-main': {
    file: 'perilla-main.jpg',
    author: 'Bijay Chaurasia',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Green_Perrila_(Beefsteak_plant)-IMG_0543.jpg',
    title: 'Perilla frutescens (들깨·깻잎)',
  },
  'napa-cabbage-main': {
    file: 'napa-cabbage-main.jpg',
    author: 'Krzysztof Ziarnek, Kenraiz',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Brassica_rapa_subsp._pekinensis_%27Manoko%27_kz01.jpg',
    title: 'Brassica rapa subsp. pekinensis (배추)',
  },
  'leaf-mustard-main': {
    file: 'leaf-mustard-main.jpg',
    author: 'Goldlocki',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:RoterSenfRedGiantBlatt.jpg',
    title: 'Brassica juncea (갓)',
  },
  'kale-main': {
    file: 'kale-main.jpg',
    author: 'Ruth Hartnup from Vancouver, Canada',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Raindrops_on_curly_kale_(8148802845).jpg',
    title: 'Brassica oleracea var. acephala (케일)',
  },
  'bok-choy-main': {
    file: 'bok-choy-main.jpg',
    author: 'claralieu',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bok_Choy_-30.jpg',
    title: 'Brassica rapa subsp. chinensis (청경채)',
  },
  'garlic-chives-main': {
    file: 'garlic-chives-main.jpg',
    author: 'Mohamed Yahya',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Garlic_chives_1.jpg',
    title: 'Allium tuberosum (부추)',
  },
  'welsh-onion-main': {
    file: 'welsh-onion-main.jpg',
    author: 'Bùi Thụy Đào Nguyên',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nh%E1%BB%AFng_b%E1%BB%A5i_h%C3%A0nh_ta.jpg',
    title: 'Allium fistulosum (대파)',
  },
  'scallion-main': {
    file: 'scallion-main.jpg',
    author: 'Choikwangmo9',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:2020-03-13_21.10.21_%EB%8B%A4%EB%93%AC%EC%9D%80_%EC%AA%BD%ED%8C%8C_korea_tree_onion.jpg',
    title: 'Allium x wakegi (쪽파)',
  },
  'onion-main': {
    file: 'onion-main.jpg',
    author: 'Schlaghecken Josef',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Zwiebel_Kurz_vor_der_Rodung--Josef_Schlaghecken.jpg',
    title: 'Allium cepa (양파)',
  },
  'garlic-main': {
    file: 'garlic-main.jpg',
    author: 'Peachyeung316',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:A_plate_of_Gralic_at_home.jpg',
    title: 'Allium sativum (마늘)',
  },
  'ginger-main': {
    file: 'ginger-main.jpg',
    author: 'Koorosh Orooj',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ginger_.jpg',
    title: 'Zingiber officinale (생강)',
  },
  // ② 열한째 배치 = 채소(열매·뿌리) 13종(비화훼 넷째 그룹). 가식부(열매·덩이줄기·
  //    뿌리)가 대표라 그 부위로 골랐다. 감자=감자 바구니, 무=흰 다이콘, 가지=줄기에
  //    달린 길쭉 보라가지, 호박=애호박 자유 사진이 없어 정직하게 늙은호박류로 매핑. ──
  'tomato-main': {
    file: 'tomato-main.jpg',
    author: 'Jubair Bin Iqbal',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bangladeshi_Tomato.jpg',
    title: 'Solanum lycopersicum (토마토)',
  },
  'pepper-main': {
    file: 'pepper-main.jpg',
    author: 'yoopilsun',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Korean_chillies.jpg',
    title: 'Capsicum annuum (고추)',
  },
  'eggplant-main': {
    file: 'eggplant-main.jpg',
    author: 'Kolforn',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:-2017-06-21_Aubergine,_Trimingham.JPG',
    title: 'Solanum melongena (가지)',
  },
  'potato-main': {
    file: 'potato-main.jpg',
    author: 'Peachyeung316',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:A_basket_of_Potatoes_at_Tuen_Mun.jpg',
    title: 'Solanum tuberosum (감자)',
  },
  'cucumber-main': {
    file: 'cucumber-main.jpg',
    author: 'Michael Garlick',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:RHS_Bridgewater,_The_Fruit_House,_Cucumbers_-_geograph.org.uk_-_7017377.jpg',
    title: 'Cucumis sativus (오이)',
  },
  'squash-main': {
    file: 'squash-main.jpg',
    author: 'George Chernilevsky',
    license: 'Public Domain',
    licenseUrl: 'https://creativecommons.org/publicdomain/mark/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cucurbita_2018_G2.jpg',
    title: 'Cucurbita spp. (애호박·호박)',
  },
  'korean-melon-main': {
    file: 'korean-melon-main.jpg',
    author: 'Uo3rt',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ougon-makuwa.JPG',
    title: 'Cucumis melo var. makuwa (참외)',
  },
  'radish-main': {
    file: 'radish-main.jpg',
    author: 'Daderot',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Daikon_-_Harbourside_Market,_Wellington,_New_Zealand_-_DSC09775.jpg',
    title: 'Raphanus sativus (무)',
  },
  'carrot-main': {
    file: 'carrot-main.jpg',
    author: 'woodleywonderworks',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Carrot_harvest.jpg',
    title: 'Daucus carota (당근)',
  },
  'sweet-potato-main': {
    file: 'sweet-potato-main.jpg',
    author: "Filo gèn'",
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ipomoea_batatas_-_Tubers.jpg',
    title: 'Ipomoea batatas (고구마)',
  },
  'corn-main': {
    file: 'corn-main.jpg',
    author: 'Forest and Kim Starr',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Starr-200723-7940-Zea_mays-Hawaiian_Supersweet_10_harvested_cobs-Hawea_Pl_Olinda-Maui_(50336255331).jpg',
    title: 'Zea mays (옥수수)',
  },
  'kidney-bean-main': {
    file: 'kidney-bean-main.jpg',
    author: 'Bean appreciator',
    license: 'CC0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Red_kidney_beans_2024-11-27.jpg',
    title: 'Phaseolus vulgaris (강낭콩)',
  },
  'pea-main': {
    file: 'pea-main.jpg',
    author: 'Kolforn',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:-2019-07-29_Forming_garden_pea_pods_(Pisum_sativum),_Trimingham.JPG',
    title: 'Pisum sativum (완두)',
  },
}

export function getCcPhoto(speciesId: string): CcPhoto | undefined {
  return ccPhotos[speciesId]
}
